
BOOTLOADER = bootloader

OBJ-BOOTLOADER += $(BOOTLOADER)/bootloader.o
OBJ-BOOTLOADER += $(BOOTLOADER)/usb.o
OBJ-BOOTLOADER += $(BOOTLOADER)/isp_self.o
OBJ-BOOTLOADER += $(BOOTLOADER)/isp_ext.o

TEXT = 0x7000